---
title: "2 Basic Data Manipulation"
author: "Mohammadamin Firouzi"
date: "2025-02-20"
output: html_document
---

# Basic Data Manipulation

#### Data Frames

We start by creating vectors for years and prices, and then combine them into a matrix.

```{r message=FALSE, warning=FALSE}

year = c(2018, 2019, 2020, 2021, 2022, 2023, 2024)
price1 = c(10, 12, 12.5, 12, 14, 17, 17)
price2 = c(5, 7, 7, 7, 9, 10, 10)
price3 = c(34, 34, 34.5, 35, 38, 40, 41)

pricemat = cbind(price1, price2, price3)
rownames(pricemat) = year

pricemat
```

#### Creating a Data Frame

```{r message=FALSE, warning=FALSE}

pricedata = data.frame(pricemat)
pricedata

class(pricedata)
```

#### Accessing a Single Variable

```{r message=FALSE, warning=FALSE}

pricedata[, "price1"]
pricedata$price1
```

#### Generating a New Variable

```{r message=FALSE, warning=FALSE}

pricedata$averageprice = (pricedata$price1 + pricedata$price2 + pricedata$price3) / 3
pricedata
```

#### Subsetting Data

```{r message=FALSE, warning=FALSE}

pricedata
subset(pricedata, averageprice < 21)
subset(pricedata, averageprice < 21 & averageprice > 17)
```

#### Saving and Loading Data

```{r message=FALSE, warning=FALSE}

save(pricedata, file = "pricedata.RData")
load("pricedata.RData")
pricedata
```

#### Basic Information on a Data Set

```{r message=FALSE, warning=FALSE}

head(pricedata)
str(pricedata)
colMeans(pricedata)
```

------------------------------------------------------------------------

#### Import of Text Files

```{r message=FALSE, warning=FALSE}

getwd()
setwd("C:/Users/Mohammadamin/Desktop/TA/Metrics I")

newdata = read.table("data.csv", sep =",", header = TRUE)
```

#### Import of Other Data Formats

```{r message=FALSE, warning=FALSE}

# install.packages("rio")
library(rio)
newdata = import("data.csv")
colnames(newdata) = c("Country", seq(1974, 2022))
rm(newdata)

wage1 = import("C:/Users/Mohammadamin/Desktop/TA/Metrics I/wage1.dta")
rm(wage1)

wage1 = import("http://fmwww.bc.edu/ec-p/data/wooldridge/wage1.dta")
rm(wage1)

help(rio)
```

------------------------------------------------------------------------

#### Wooldridge Package Example

```{r message=FALSE, warning=FALSE}

# install.packages("wooldridge")
data(wage1, package = "wooldridge")
```
